services:
  db:
    image: postgres:16-alpine
    container_name: pg-notifications
    environment:
      POSTGRES_DB: notifications_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 40022120

    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notifications_service"]
      interval: 5s
      timeout: 3s
      retries: 10

  notifications-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: notifications-service:dev
    container_name: notifications-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: "8085"

      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/notifications_service"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "40022120"

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      EVENTS_BASE_URL: "http://host.docker.internal:8083"
      # NOTIFICATIONS_BASE_URL: "http://host.docker.internal:8085"
    ports:
      - "8085:8085"

volumes:
  pgdata:
